name: check npm & node version
on: push 
jobs: 
    first-job: 
      runs-on: ubuntu-latest
      steps:
        - run:  node --version
        - run:  npm --version
                   -  
         
          
