name: run spript bash
on: [workflow_dispatch]
jobs:
     run_script:
          runs-on: ${{ matrix.os }}
          strategy:
             os: [ubuntu-latest,windows-latest]
          steps:
            - name: checkout repository
              uses: actions/checkout@v2

            - name: run script bash 
              run:  echo "heeeey"
             
          
