name: run spript bash
on: [workflow_dispatch]
jobs:
      job1:
          runs-on: ${{ matrix.os }}
          strategy:
            matrix:
              os: [ubuntu-latest]
          steps:
            - name: run script bash1
              run:  echo heeeey
      job2:
          needs: job1
          runs-on: ${{ matrix.os }}
          strategy:
            matrix:
              os: [ubuntu-latest]
          steps:
            - name: run script bash2
              run: echo salim
      
             
          
